Improve update-dot-files to better handle conflicts
For some reason using the GIT_DIR method ends up emitting an error
message about changes being overwritten:

    Updating cb06c95..23bd7e3
    error: Your local changes to the following files would be overwritten by merge:
	    .bashrc
    Please, commit your changes or stash them before you can merge.
    Aborting